import { TypingChallenge } from '../../types';

const FALLBACK_CREATED_AT = '2025-01-01T00:00:00.000Z';

// Writing-focused challenges used when Supabase has no prose content available.
export const WRITING_FALLBACK_CHALLENGES: TypingChallenge[] = [
  {
    id: 'fallback-writing-ocean-discovery',
    title: 'Ocean Discovery',
    text_content: 'The vast ocean depths remain largely unexplored, holding secrets that could reshape what we know about life on Earth.',
    difficulty: 'Easy',
    category: 'Science',
    length_type: 'Sprint',
    created_at: FALLBACK_CREATED_AT,
    is_custom: true,
    word_count: 23,
    char_count: 145,
  },
  {
    id: 'fallback-writing-literary-echoes',
    title: 'Literary Echoes',
    text_content: 'Great stories echo across generations, teaching empathy, sharpening language, and inviting readers to see the world through new eyes.',
    difficulty: 'Easy',
    category: 'ELA',
    length_type: 'Sprint',
    created_at: FALLBACK_CREATED_AT,
    is_custom: true,
    word_count: 23,
    char_count: 143,
  },
  {
    id: 'fallback-writing-renaissance-sparks',
    title: 'Renaissance Sparks',
    text_content: 'The Renaissance ignited when scholars revisited classical ideas, blending art, science, and philosophy to spark a new era of curiosity.',
    difficulty: 'Medium',
    category: 'History',
    length_type: 'Medium',
    created_at: FALLBACK_CREATED_AT,
    is_custom: true,
    word_count: 28,
    char_count: 170,
  },
  {
    id: 'fallback-writing-mindful-focus',
    title: 'Mindful Focus',
    text_content: 'Regular mindfulness practice can steady attention, lower stress, and help students process complex reading without feeling overwhelmed.',
    difficulty: 'Medium',
    category: 'Health',
    length_type: 'Medium',
    created_at: FALLBACK_CREATED_AT,
    is_custom: true,
    word_count: 24,
    char_count: 150,
  },
  {
    id: 'fallback-writing-quantum-weirdness',
    title: 'Quantum Weirdness',
    text_content: 'Quantum mechanics shows particles in two states at once, reminding us that even the smallest pieces of matter can defy simple explanations.',
    difficulty: 'Hard',
    category: 'Science',
    length_type: 'Medium',
    created_at: FALLBACK_CREATED_AT,
    is_custom: true,
    word_count: 28,
    char_count: 171,
  },
  {
    id: 'fallback-writing-digital-revolution',
    title: 'Digital Revolution',
    text_content: 'The internet transformed how we read, write, and learn, turning classrooms into connected labs where articles, data, and ideas move instantly.',
    difficulty: 'Medium',
    category: 'Technology',
    length_type: 'Medium',
    created_at: FALLBACK_CREATED_AT,
    is_custom: true,
    word_count: 28,
    char_count: 176,
  },
  {
    id: 'fallback-writing-global-markets',
    title: 'Global Markets',
    text_content: 'Modern economies link shoppers, factories, and policies across continents, so a drought in one country can raise grocery prices in another.',
    difficulty: 'Hard',
    category: 'Economics',
    length_type: 'Medium',
    created_at: FALLBACK_CREATED_AT,
    is_custom: true,
    word_count: 28,
    char_count: 167,
  },
  {
    id: 'fallback-writing-article-excerpt',
    title: 'Article Excerpt: Community Library',
    text_content: 'A small-town library reinvented itself with after-school tutoring, bilingual story hours, and a quiet room for students who need a steady place to read.',
    difficulty: 'Easy',
    category: 'Article',
    length_type: 'Medium',
    created_at: FALLBACK_CREATED_AT,
    is_custom: true,
    word_count: 34,
    char_count: 199,
  },
  {
    id: 'fallback-writing-reading-strategies',
    title: 'Reading Strategies',
    text_content: 'Strong readers preview text, annotate key ideas, and pause to summarize so complex passages feel less intimidating and more meaningful.',
    difficulty: 'Easy',
    category: 'Reading',
    length_type: 'Sprint',
    created_at: FALLBACK_CREATED_AT,
    is_custom: true,
    word_count: 23,
    char_count: 144,
  },
];
